## 2022
- id: doi:10.1038/s41588-022-01078-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41588-022-01078-z/MediaObjects/41588_2022_1078_Fig2_HTML.png?as=webp
  date: 2022-6-2
  extra-links:
    - type: pubmed
      link: https://pubmed.ncbi.nlm.nih.gov/35654975/
      text: PubMed

## 2012
- id: doi:10.1016/S0140-6736(12)60312-2
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0140673612603122-gr2.jpg
  date: 2012-8-11
  extra-links:
    - type: pubmed
      link: https://pubmed.ncbi.nlm.nih.gov/22607825/
      text: PubMed
    - type: pdf
      link: https://www.sciencedirect.com/science/article/pii/S0140673612603122/pdfft?md5=cbb9b0840b893a8d12558a349e33c289&pid=1-s2.0-S0140673612603122-main.pdf
      text: PDF
    - type: news
      link: https://www.nytimes.com/2012/05/17/health/research/hdl-good-cholesterol-found-not-to-cut-heart-risk.html
      text: NYT
  tags:
    - Mendelian Randomization
    - Complex Traits
    - Methods
    - Lead Effort
  
## 2006
- id: doi:10.1371/journal.pbio.0040072
  image: https://journals.plos.org/plosbiology/article/figure/image?size=medium&id=10.1371/journal.pbio.0040072.g001
  date: 2006-3-7
  repo: https://github.com/bvoightlab/iHS_calc
  extra-links:
    - type: pubmed
      link: https://pubmed.ncbi.nlm.nih.gov/16494531/
      text: PubMed
    - type: pdf
      link: https://journals.plos.org/plosbiology/article/file?id=10.1371/journal.pbio.0040072&type=printable
      text: PDF
    - type: source
      link: https://github.com/bvoightlab/iHS_calc
      text: GitHub
    - type: news
      link: https://www.nytimes.com/2006/03/07/science/still-evolving-human-genes-tell-new-story.html
      text: NYT
  tags:
    - PopGen
    - Methods
    - Lead Effort

## excludes
#- id: doi:10.1016/j.csbj.2020.05.017
#  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
#  date: 2020-6-2
#  extra-links:
#    - type: manubot
#      link: https://greenelab.github.io/knowledge-graph-review/
#  tags:
#    - knowledge graphs

#- id: doi:10.1371/journal.pcbi.1007128
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  repo: greenelab/meta-review
#  extra-links:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/

#- id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
#  extra-links:
#    - type: preprint
#      link: https://doi.org/10.7287/peerj.preprints.3100v1
#    - type: manubot
#      link: https://greenelab.github.io/scihub-manuscript/
#    - type: source
#      link: https://github.com/greenelab/scihub-manuscript
#      text: Manuscript source
#    - type: source
#      link: https://github.com/greenelab/scihub
#      text: Analyses source
